// Generated by scripts/build-edtech-data.mjs. Do not edit manually.
import type { EdtechSnapshot, TeacherWebAppSummary } from "./edtech-types";

export const edtechSnapshot: EdtechSnapshot = {
  "asOf": "2026-07-24",
  "sourceCommit": "9819ddad0288e65279803c8523d37fdc0ea0b0d4",
  "denominators": {
    "all": 174,
    "elementary": 86,
    "middle": 51,
    "high": 37
  },
  "tools": [
    {
      "id": "패들렛",
      "name": "패들렛",
      "group": "협업·공유",
      "purpose": "게시판과 캔버스에 자료·의견·결과물을 함께 모으는 실시간 협업 공간",
      "counts": {
        "all": 54,
        "elementary": 35,
        "middle": 13,
        "high": 6
      },
      "rates": {
        "all": 31,
        "elementary": 40.7,
        "middle": 25.5,
        "high": 16.2
      },
      "ranks": {
        "all": 1,
        "elementary": 1,
        "middle": 1,
        "high": 3
      },
      "related": {
        "all": [
          "캔바",
          "Claude",
          "심스페이스",
          "ChatGPT",
          "Gemini"
        ],
        "elementary": [
          "캔바",
          "심스페이스",
          "매쓰홀릭",
          "아트봉봉",
          "클래시파이"
        ],
        "middle": [
          "캔바",
          "Gemini",
          "멘티미터",
          "클리포",
          "Claude"
        ],
        "high": [
          "캔바",
          "Claude",
          "리로스쿨",
          "북크리에이터",
          "임팩트스페이스"
        ]
      }
    },
    {
      "id": "캔바",
      "name": "캔바",
      "group": "콘텐츠 제작",
      "purpose": "발표자료·이미지·영상·웹 콘텐츠를 함께 설계하고 제작하는 시각 저작 도구",
      "counts": {
        "all": 41,
        "elementary": 24,
        "middle": 12,
        "high": 5
      },
      "rates": {
        "all": 23.6,
        "elementary": 27.9,
        "middle": 23.5,
        "high": 13.5
      },
      "ranks": {
        "all": 2,
        "elementary": 2,
        "middle": 2,
        "high": 5
      },
      "related": {
        "all": [
          "패들렛",
          "심스페이스",
          "클리포",
          "클래시파이",
          "ChatGPT"
        ],
        "elementary": [
          "패들렛",
          "심스페이스",
          "클래시파이",
          "아트봉봉",
          "자작자작"
        ],
        "middle": [
          "패들렛",
          "Gemini",
          "클리포",
          "ChatGPT",
          "Claude"
        ],
        "high": [
          "클리포",
          "패들렛",
          "노션",
          "북크리에이터",
          "플랭스쿨"
        ]
      }
    },
    {
      "id": "gemini",
      "name": "Gemini",
      "group": "생성형 AI",
      "purpose": "텍스트·이미지·자료 분석과 생성을 지원하는 멀티모달 생성형 AI",
      "counts": {
        "all": 24,
        "elementary": 5,
        "middle": 11,
        "high": 8
      },
      "rates": {
        "all": 13.8,
        "elementary": 5.8,
        "middle": 21.6,
        "high": 21.6
      },
      "ranks": {
        "all": 3,
        "elementary": 9,
        "middle": 3,
        "high": 2
      },
      "related": {
        "all": [
          "ChatGPT",
          "Claude",
          "패들렛",
          "NotebookLM",
          "노션"
        ],
        "elementary": [
          "구글 클래스룸",
          "매쓰홀릭",
          "엔트리",
          "패들렛",
          "Brisk Teaching"
        ],
        "middle": [
          "캔바",
          "패들렛",
          "ChatGPT",
          "NotebookLM",
          "노션"
        ],
        "high": [
          "Claude",
          "ChatGPT",
          "노션",
          "NotebookLM",
          "데스모스"
        ]
      }
    },
    {
      "id": "claude",
      "name": "Claude",
      "group": "생성형 AI",
      "purpose": "긴 문서 분석·글쓰기·아이디어 정리와 코딩을 지원하는 생성형 AI",
      "counts": {
        "all": 16,
        "elementary": 3,
        "middle": 5,
        "high": 8
      },
      "rates": {
        "all": 9.2,
        "elementary": 3.5,
        "middle": 9.8,
        "high": 21.6
      },
      "ranks": {
        "all": 4,
        "elementary": 21,
        "middle": 5,
        "high": 1
      },
      "related": {
        "all": [
          "Gemini",
          "패들렛",
          "ChatGPT",
          "클리포",
          "노션"
        ],
        "elementary": [
          "블루킷",
          "ChatGPT",
          "클래스카드",
          "클리포",
          "패들렛"
        ],
        "middle": [
          "캔바",
          "클리포",
          "패들렛",
          "마이클AI",
          "Gemini"
        ],
        "high": [
          "Gemini",
          "ChatGPT",
          "노션",
          "패들렛",
          "리로스쿨"
        ]
      }
    },
    {
      "id": "심스페이스",
      "name": "심스페이스",
      "group": "학습관리",
      "purpose": "학생의 감정과 관계 데이터를 살펴 상담과 사회정서학습을 돕는 플랫폼",
      "counts": {
        "all": 13,
        "elementary": 11,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 7.5,
        "elementary": 12.8,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 5,
        "elementary": 3,
        "middle": 16,
        "high": 63
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "매쓰홀릭",
          "센스쿨",
          "풀리수학"
        ],
        "elementary": [
          "캔바",
          "패들렛",
          "매쓰홀릭",
          "풀리수학",
          "센스쿨"
        ],
        "middle": [
          "센스쿨",
          "캔바",
          "ChatGPT",
          "Gemini"
        ],
        "high": []
      }
    },
    {
      "id": "notebooklm",
      "name": "NotebookLM",
      "group": "생성형 AI",
      "purpose": "교사가 넣은 자료를 근거로 요약·질문·학습 자료 생성을 지원하는 AI 도구",
      "counts": {
        "all": 12,
        "elementary": 2,
        "middle": 5,
        "high": 5
      },
      "rates": {
        "all": 6.9,
        "elementary": 2.3,
        "middle": 9.8,
        "high": 13.5
      },
      "ranks": {
        "all": 6,
        "elementary": 35,
        "middle": 6,
        "high": 7
      },
      "related": {
        "all": [
          "Gemini",
          "패들렛",
          "Snorkl",
          "데스모스",
          "띵커벨"
        ],
        "elementary": [
          "아트봉봉",
          "자작자작",
          "패들렛"
        ],
        "middle": [
          "패들렛",
          "Gemini",
          "뤼튼",
          "북크리에이터",
          "스쿨플랫"
        ],
        "high": [
          "Gemini",
          "Snorkl",
          "데스모스",
          "띵커벨",
          "이음AI"
        ]
      }
    },
    {
      "id": "chatgpt",
      "name": "ChatGPT",
      "group": "생성형 AI",
      "purpose": "대화형 자료 생성·분석·아이디어 탐색을 지원하는 생성형 AI",
      "counts": {
        "all": 11,
        "elementary": 3,
        "middle": 3,
        "high": 5
      },
      "rates": {
        "all": 6.3,
        "elementary": 3.5,
        "middle": 5.9,
        "high": 13.5
      },
      "ranks": {
        "all": 7,
        "elementary": 20,
        "middle": 10,
        "high": 6
      },
      "related": {
        "all": [
          "Gemini",
          "Claude",
          "패들렛",
          "캔바",
          "SUNO"
        ],
        "elementary": [
          "패들렛",
          "Claude",
          "블루킷",
          "캔바",
          "클래시파이"
        ],
        "middle": [
          "캔바",
          "Gemini",
          "멘티미터",
          "심스페이스",
          "패들렛"
        ],
        "high": [
          "Claude",
          "Gemini",
          "구글 클래스룸",
          "노션",
          "리로스쿨"
        ]
      }
    },
    {
      "id": "zep-젭퀴즈",
      "name": "ZEP·젭퀴즈",
      "group": "퀴즈·참여",
      "purpose": "메타버스형 참여 공간과 게임형 퀴즈를 결합한 수업 참여 도구",
      "counts": {
        "all": 11,
        "elementary": 7,
        "middle": 3,
        "high": 1
      },
      "rates": {
        "all": 6.3,
        "elementary": 8.1,
        "middle": 5.9,
        "high": 2.7
      },
      "ranks": {
        "all": 8,
        "elementary": 6,
        "middle": 11,
        "high": 42
      },
      "related": {
        "all": [
          "패들렛",
          "캔바",
          "토도한글",
          "띵커벨",
          "매쓰홀릭"
        ],
        "elementary": [
          "패들렛",
          "캔바",
          "토도한글",
          "띵커벨",
          "빅카인즈"
        ],
        "middle": [
          "매쓰홀릭",
          "우리반",
          "카훗",
          "클래스팅 AI"
        ],
        "high": [
          "MS Teams"
        ]
      }
    },
    {
      "id": "google-workspace",
      "name": "Google Workspace",
      "group": "협업·공유",
      "purpose": "문서·슬라이드·시트·드라이브에서 공동 편집과 자료 공유를 지원하는 협업 도구",
      "counts": {
        "all": 10,
        "elementary": 3,
        "middle": 4,
        "high": 3
      },
      "rates": {
        "all": 5.7,
        "elementary": 3.5,
        "middle": 7.8,
        "high": 8.1
      },
      "ranks": {
        "all": 9,
        "elementary": 22,
        "middle": 7,
        "high": 10
      },
      "related": {
        "all": [
          "노션",
          "캔바",
          "왓퀴즈",
          "클래스카드",
          "패들렛"
        ],
        "elementary": [
          "왓퀴즈",
          "패들렛",
          "ZEP·젭퀴즈"
        ],
        "middle": [
          "캔바",
          "클래스카드",
          "SEN스쿨"
        ],
        "high": [
          "노션",
          "캔바",
          "Claude",
          "Gemini",
          "NotebookLM"
        ]
      }
    },
    {
      "id": "매쓰홀릭",
      "name": "매쓰홀릭",
      "group": "교과·맞춤형",
      "purpose": "수학 문제은행과 진단·추천 학습을 제공하는 수학 AI 코스웨어",
      "counts": {
        "all": 9,
        "elementary": 8,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 5.2,
        "elementary": 9.3,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 10,
        "elementary": 4,
        "middle": 28,
        "high": 54
      },
      "related": {
        "all": [
          "심스페이스",
          "패들렛",
          "구글 클래스룸",
          "문제G",
          "우리반"
        ],
        "elementary": [
          "심스페이스",
          "패들렛",
          "구글 클래스룸",
          "문제G",
          "우리반"
        ],
        "middle": [
          "카훗",
          "ZEP·젭퀴즈"
        ],
        "high": []
      }
    },
    {
      "id": "클리포",
      "name": "클리포",
      "group": "퀴즈·참여",
      "purpose": "수행평가 설계·AI 채점·맞춤 피드백·기록을 지원하는 평가 도구",
      "counts": {
        "all": 9,
        "elementary": 1,
        "middle": 5,
        "high": 3
      },
      "rates": {
        "all": 5.2,
        "elementary": 1.2,
        "middle": 9.8,
        "high": 8.1
      },
      "ranks": {
        "all": 11,
        "elementary": 59,
        "middle": 4,
        "high": 9
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "Claude",
          "SUNO",
          "블루킷"
        ],
        "elementary": [
          "블루킷",
          "ChatGPT",
          "Claude",
          "SUNO"
        ],
        "middle": [
          "캔바",
          "패들렛",
          "Claude",
          "투닝",
          "Brisk Teaching"
        ],
        "high": [
          "캔바",
          "원아워",
          "클래스카드",
          "패들렛",
          "SUNO"
        ]
      }
    },
    {
      "id": "구글-클래스룸",
      "name": "구글 클래스룸",
      "group": "학습관리",
      "purpose": "과제 배부·제출·피드백과 수업 자료 관리를 지원하는 학습관리 플랫폼",
      "counts": {
        "all": 8,
        "elementary": 7,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 4.6,
        "elementary": 8.1,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 12,
        "elementary": 5,
        "middle": 48,
        "high": 17
      },
      "related": {
        "all": [
          "매쓰홀릭",
          "센스쿨",
          "똑똑수학탐험대",
          "문제G",
          "심스페이스"
        ],
        "elementary": [
          "매쓰홀릭",
          "센스쿨",
          "똑똑수학탐험대",
          "문제G",
          "심스페이스"
        ],
        "middle": [],
        "high": [
          "ChatGPT",
          "Veo3"
        ]
      }
    },
    {
      "id": "노션",
      "name": "노션",
      "group": "협업·공유",
      "purpose": "문서·데이터베이스·일정·업무를 함께 관리하는 협업 공간",
      "counts": {
        "all": 7,
        "elementary": 0,
        "middle": 2,
        "high": 5
      },
      "rates": {
        "all": 4,
        "elementary": 0,
        "middle": 3.9,
        "high": 13.5
      },
      "ranks": {
        "all": 13,
        "elementary": 74,
        "middle": 12,
        "high": 4
      },
      "related": {
        "all": [
          "Gemini",
          "Claude",
          "Google Workspace",
          "오르조 클래스",
          "카훗"
        ],
        "elementary": [],
        "middle": [
          "패들렛",
          "Gemini"
        ],
        "high": [
          "Claude",
          "Gemini",
          "Google Workspace",
          "오르조 클래스",
          "카훗"
        ]
      }
    },
    {
      "id": "snorkl",
      "name": "Snorkl",
      "group": "퀴즈·참여",
      "purpose": "학생이 말·글·그림으로 설명하면 AI 피드백을 제공하는 형성평가 플랫폼",
      "counts": {
        "all": 7,
        "elementary": 1,
        "middle": 1,
        "high": 5
      },
      "rates": {
        "all": 4,
        "elementary": 1.2,
        "middle": 2,
        "high": 13.5
      },
      "ranks": {
        "all": 14,
        "elementary": 73,
        "middle": 45,
        "high": 8
      },
      "related": {
        "all": [
          "NotebookLM",
          "데스모스",
          "심스페이스",
          "채움AI",
          "퀴즈앤"
        ],
        "elementary": [
          "심스페이스",
          "풀리수학",
          "E-GPT"
        ],
        "middle": [
          "채움AI",
          "Typecast"
        ],
        "high": [
          "NotebookLM",
          "데스모스",
          "퀴즈앤",
          "클래스카드",
          "키노트"
        ]
      }
    },
    {
      "id": "suno",
      "name": "SUNO",
      "group": "콘텐츠 제작",
      "purpose": "텍스트 지시로 노래와 배경음악을 만드는 생성형 음악 도구",
      "counts": {
        "all": 7,
        "elementary": 3,
        "middle": 2,
        "high": 2
      },
      "rates": {
        "all": 4,
        "elementary": 3.5,
        "middle": 3.9,
        "high": 5.4
      },
      "ranks": {
        "all": 15,
        "elementary": 23,
        "middle": 24,
        "high": 16
      },
      "related": {
        "all": [
          "패들렛",
          "ChatGPT",
          "캔바",
          "클리포",
          "멘티미터"
        ],
        "elementary": [
          "미리캔버스",
          "블루킷",
          "캡컷",
          "클리포",
          "통그라미"
        ],
        "middle": [
          "패들렛",
          "멘티미터",
          "캔바",
          "ChatGPT"
        ],
        "high": [
          "캔바",
          "클리포",
          "패들렛",
          "ChatGPT",
          "Gemini"
        ]
      }
    },
    {
      "id": "클래스카드",
      "name": "클래스카드",
      "group": "언어·문해",
      "purpose": "영어 어휘·문장 세트를 게임과 반복 학습으로 익히는 언어 학습 도구",
      "counts": {
        "all": 6,
        "elementary": 2,
        "middle": 2,
        "high": 2
      },
      "rates": {
        "all": 3.4,
        "elementary": 2.3,
        "middle": 3.9,
        "high": 5.4
      },
      "ranks": {
        "all": 16,
        "elementary": 30,
        "middle": 18,
        "high": 12
      },
      "related": {
        "all": [
          "러니",
          "블루킷",
          "원아워",
          "체리팟",
          "클리포"
        ],
        "elementary": [
          "블루킷",
          "토도한글",
          "패들렛",
          "플랭스쿨",
          "Claude"
        ],
        "middle": [
          "러니",
          "체리팟",
          "Brisk Teaching",
          "Google Workspace"
        ],
        "high": [
          "원아워",
          "클리포",
          "Redmenta",
          "Snorkl"
        ]
      }
    },
    {
      "id": "클래스팅-ai",
      "name": "클래스팅 AI",
      "group": "학습관리",
      "purpose": "학급관리와 AI 기반 진단·맞춤 학습을 결합한 교육 플랫폼",
      "counts": {
        "all": 6,
        "elementary": 3,
        "middle": 2,
        "high": 1
      },
      "rates": {
        "all": 3.4,
        "elementary": 3.5,
        "middle": 3.9,
        "high": 2.7
      },
      "ranks": {
        "all": 17,
        "elementary": 16,
        "middle": 19,
        "high": 30
      },
      "related": {
        "all": [
          "우리반",
          "채움AI",
          "캔바",
          "토도 시리즈",
          "패들렛"
        ],
        "elementary": [
          "캔바",
          "토도 시리즈",
          "패들렛",
          "포커스팡"
        ],
        "middle": [
          "우리반",
          "채움AI",
          "ZEP·젭퀴즈"
        ],
        "high": [
          "ChatGPT",
          "Claude",
          "Gamma",
          "Gemini",
          "MS Teams"
        ]
      }
    },
    {
      "id": "띵커벨",
      "name": "띵커벨",
      "group": "퀴즈·참여",
      "purpose": "퀴즈·토론·설문·워드클라우드·보드를 제공하는 수업 상호작용 도구",
      "counts": {
        "all": 5,
        "elementary": 3,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 2.9,
        "elementary": 3.5,
        "middle": 2,
        "high": 2.7
      },
      "ranks": {
        "all": 18,
        "elementary": 14,
        "middle": 25,
        "high": 19
      },
      "related": {
        "all": [
          "똑똑수학탐험대",
          "마인크래프트",
          "북크리에이터",
          "아이쌤GPT",
          "이음AI"
        ],
        "elementary": [
          "똑똑수학탐험대",
          "마인크래프트",
          "북크리에이터",
          "아이쌤GPT",
          "자작자작"
        ],
        "middle": [
          "클래스팅"
        ],
        "high": [
          "이음AI",
          "키위티",
          "Gemini",
          "NotebookLM"
        ]
      }
    },
    {
      "id": "블루킷",
      "name": "블루킷",
      "group": "퀴즈·참여",
      "purpose": "문항 세트를 여러 게임 모드로 운영하는 실시간 퀴즈 플랫폼",
      "counts": {
        "all": 5,
        "elementary": 5,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 2.9,
        "elementary": 5.8,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 19,
        "elementary": 7,
        "middle": 61,
        "high": 58
      },
      "related": {
        "all": [
          "패들렛",
          "Claude",
          "리드포스쿨",
          "엔트리",
          "클래스카드"
        ],
        "elementary": [
          "패들렛",
          "Claude",
          "리드포스쿨",
          "엔트리",
          "클래스카드"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "스쿨플랫",
      "name": "스쿨플랫",
      "group": "교과·맞춤형",
      "purpose": "문제은행·과제·성취 분석을 제공하는 학교 맞춤형 수학 코스웨어",
      "counts": {
        "all": 5,
        "elementary": 2,
        "middle": 2,
        "high": 1
      },
      "rates": {
        "all": 2.9,
        "elementary": 2.3,
        "middle": 3.9,
        "high": 2.7
      },
      "ranks": {
        "all": 20,
        "elementary": 26,
        "middle": 15,
        "high": 22
      },
      "related": {
        "all": [
          "캔바",
          "다했니·다했어요",
          "달달독해",
          "리딩오션스쿨",
          "토도한글"
        ],
        "elementary": [
          "다했니·다했어요",
          "달달독해",
          "리딩오션스쿨",
          "캔바",
          "토도한글"
        ],
        "middle": [
          "캔바",
          "NotebookLM"
        ],
        "high": [
          "AICE"
        ]
      }
    },
    {
      "id": "아트봉봉",
      "name": "아트봉봉",
      "group": "콘텐츠 제작",
      "purpose": "디지털 드로잉과 미술 활동 결과물 제작을 지원하는 예술교육 도구",
      "counts": {
        "all": 5,
        "elementary": 5,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 2.9,
        "elementary": 5.8,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 21,
        "elementary": 8,
        "middle": 67,
        "high": 65
      },
      "related": {
        "all": [
          "패들렛",
          "심스페이스",
          "캔바",
          "센스쿨",
          "자작자작"
        ],
        "elementary": [
          "패들렛",
          "심스페이스",
          "캔바",
          "센스쿨",
          "자작자작"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "투닝",
      "name": "투닝",
      "group": "콘텐츠 제작",
      "purpose": "웹툰·스토리·이미지 콘텐츠를 만드는 교육용 창작 도구",
      "counts": {
        "all": 5,
        "elementary": 3,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 2.9,
        "elementary": 3.5,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 22,
        "elementary": 18,
        "middle": 20,
        "high": 86
      },
      "related": {
        "all": [
          "캔바",
          "뤼튼",
          "와우아이디어스",
          "왓퀴즈",
          "클리포"
        ],
        "elementary": [
          "와우아이디어스",
          "캔바",
          "통그라미",
          "E-GPT",
          "SUNO"
        ],
        "middle": [
          "뤼튼",
          "왓퀴즈",
          "캔바",
          "클리포",
          "Gemini"
        ],
        "high": []
      }
    },
    {
      "id": "풀리수학",
      "name": "풀리수학",
      "group": "교과·맞춤형",
      "purpose": "AI 진단과 수준별 수학 문제 추천을 지원하는 코스웨어",
      "counts": {
        "all": 5,
        "elementary": 3,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 2.9,
        "elementary": 3.5,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 23,
        "elementary": 19,
        "middle": 21,
        "high": 90
      },
      "related": {
        "all": [
          "심스페이스",
          "아트봉봉",
          "앰플리파이 클래스룸",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "심스페이스",
          "아트봉봉",
          "캔바",
          "패들렛",
          "E-GPT"
        ],
        "middle": [
          "앰플리파이 클래스룸",
          "포커스팡"
        ],
        "high": []
      }
    },
    {
      "id": "brisk-teaching",
      "name": "Brisk Teaching",
      "group": "퀴즈·참여",
      "purpose": "교사의 자료 제작과 학생 글 피드백·평가를 지원하는 AI 보조 도구",
      "counts": {
        "all": 5,
        "elementary": 2,
        "middle": 3,
        "high": 0
      },
      "rates": {
        "all": 2.9,
        "elementary": 2.3,
        "middle": 5.9,
        "high": 0
      },
      "ranks": {
        "all": 24,
        "elementary": 32,
        "middle": 9,
        "high": 95
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "러니",
          "매쓰홀릭",
          "문제G",
          "이퓨처라이브러리"
        ],
        "elementary": [
          "구글 클래스룸",
          "매쓰홀릭",
          "문제G",
          "이퓨처라이브러리",
          "Gemini"
        ],
        "middle": [
          "러니",
          "체리팟",
          "클래스카드",
          "클리포",
          "패들렛"
        ],
        "high": []
      }
    },
    {
      "id": "북크리에이터",
      "name": "북크리에이터",
      "group": "콘텐츠 제작",
      "purpose": "글·이미지·음성·영상을 엮어 전자책과 학습 결과물을 만드는 저작 도구",
      "counts": {
        "all": 4,
        "elementary": 2,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 2.3,
        "elementary": 2.3,
        "middle": 2,
        "high": 2.7
      },
      "ranks": {
        "all": 25,
        "elementary": 25,
        "middle": 29,
        "high": 21
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "똑똑수학탐험대",
          "띵커벨",
          "멘티미터"
        ],
        "elementary": [
          "똑똑수학탐험대",
          "띵커벨",
          "멘티미터",
          "슬라이도",
          "캔바"
        ],
        "middle": [
          "NotebookLM",
          "SEN스쿨"
        ],
        "high": [
          "캔바",
          "패들렛"
        ]
      }
    },
    {
      "id": "센스쿨",
      "name": "센스쿨",
      "group": "학습관리",
      "purpose": "학교 계정과 여러 교육 서비스를 연결해 수업·학급 운영을 지원하는 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 3,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 2.3,
        "elementary": 3.5,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 26,
        "elementary": 15,
        "middle": 30,
        "high": 60
      },
      "related": {
        "all": [
          "심스페이스",
          "구글 클래스룸",
          "아트봉봉"
        ],
        "elementary": [
          "구글 클래스룸",
          "심스페이스",
          "아트봉봉"
        ],
        "middle": [
          "심스페이스"
        ],
        "high": []
      }
    },
    {
      "id": "엔트리",
      "name": "엔트리",
      "group": "코딩·컴퓨팅",
      "purpose": "블록 코딩과 AI·데이터 활동을 지원하는 교육용 프로그래밍 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 4,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 2.3,
        "elementary": 4.7,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 27,
        "elementary": 10,
        "middle": 70,
        "high": 69
      },
      "related": {
        "all": [
          "패들렛",
          "리드포스쿨",
          "블루킷",
          "캔바",
          "클래시파이"
        ],
        "elementary": [
          "패들렛",
          "리드포스쿨",
          "블루킷",
          "캔바",
          "클래시파이"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "자작자작",
      "name": "자작자작",
      "group": "언어·문해",
      "purpose": "학생의 글쓰기 과정과 교사 피드백을 연결하는 디지털 글쓰기 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 4,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 2.3,
        "elementary": 4.7,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 28,
        "elementary": 11,
        "middle": 78,
        "high": 76
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "띵커벨",
          "아트봉봉",
          "NotebookLM"
        ],
        "elementary": [
          "캔바",
          "패들렛",
          "띵커벨",
          "아트봉봉",
          "NotebookLM"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "토도한글",
      "name": "토도한글",
      "group": "언어·문해",
      "purpose": "유아·초등 초기 문해의 한글 읽기와 쓰기를 돕는 단계형 학습 앱",
      "counts": {
        "all": 4,
        "elementary": 4,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 2.3,
        "elementary": 4.7,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 29,
        "elementary": 12,
        "middle": 88,
        "high": 84
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "ZEP·젭퀴즈",
          "다했니·다했어요",
          "달달독해"
        ],
        "elementary": [
          "캔바",
          "패들렛",
          "ZEP·젭퀴즈",
          "다했니·다했어요",
          "달달독해"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "플랭스쿨",
      "name": "플랭스쿨",
      "group": "학습관리",
      "purpose": "교과 학습 콘텐츠와 학생 진도·과제를 운영하는 학교용 학습 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 2,
        "middle": 0,
        "high": 2
      },
      "rates": {
        "all": 2.3,
        "elementary": 2.3,
        "middle": 0,
        "high": 5.4
      },
      "ranks": {
        "all": 30,
        "elementary": 31,
        "middle": 90,
        "high": 13
      },
      "related": {
        "all": [
          "캔바",
          "블루킷",
          "아트봉봉",
          "클래스카드",
          "패들렛"
        ],
        "elementary": [
          "블루킷",
          "아트봉봉",
          "캔바",
          "클래스카드",
          "패들렛"
        ],
        "middle": [],
        "high": [
          "캔바",
          "Kuula",
          "Mizou"
        ]
      }
    },
    {
      "id": "mizou",
      "name": "Mizou",
      "group": "언어·문해",
      "purpose": "교사가 학습 목적의 대화형 챗봇을 구성해 언어 활동에 활용하는 도구",
      "counts": {
        "all": 4,
        "elementary": 2,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 2.3,
        "elementary": 2.3,
        "middle": 2,
        "high": 2.7
      },
      "ranks": {
        "all": 31,
        "elementary": 34,
        "middle": 42,
        "high": 40
      },
      "related": {
        "all": [
          "채움AI",
          "캔바",
          "플랭스쿨",
          "Brisk Teaching",
          "Gemini"
        ],
        "elementary": [
          "캔바",
          "Brisk Teaching",
          "Gemini"
        ],
        "middle": [
          "채움AI",
          "QuillBot"
        ],
        "high": [
          "플랭스쿨",
          "Kuula"
        ]
      }
    },
    {
      "id": "ms-teams",
      "name": "MS Teams",
      "group": "협업·공유",
      "purpose": "채팅·화상회의·과제·파일 공유를 한 공간에서 운영하는 협업 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 0,
        "middle": 2,
        "high": 2
      },
      "rates": {
        "all": 2.3,
        "elementary": 0,
        "middle": 3.9,
        "high": 5.4
      },
      "ranks": {
        "all": 32,
        "elementary": 103,
        "middle": 22,
        "high": 14
      },
      "related": {
        "all": [
          "Gemini",
          "클래스팅 AI",
          "클리포",
          "패들렛",
          "AlgeoMath"
        ],
        "elementary": [],
        "middle": [
          "클리포",
          "패들렛",
          "AlgeoMath",
          "Gemini",
          "MS OneNote"
        ],
        "high": [
          "클래스팅 AI",
          "ChatGPT",
          "Claude",
          "Gamma",
          "Gemini"
        ]
      }
    },
    {
      "id": "sen스쿨",
      "name": "SEN스쿨",
      "group": "학습관리",
      "purpose": "서울 교육 환경에서 수업과 학교 업무 운영을 지원하는 플랫폼",
      "counts": {
        "all": 4,
        "elementary": 2,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 2.3,
        "elementary": 2.3,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 33,
        "elementary": 36,
        "middle": 23,
        "high": 104
      },
      "related": {
        "all": [
          "북크리에이터",
          "자작자작",
          "Google Workspace",
          "NotebookLM"
        ],
        "elementary": [
          "자작자작"
        ],
        "middle": [
          "북크리에이터",
          "Google Workspace",
          "NotebookLM"
        ],
        "high": []
      }
    },
    {
      "id": "똑똑수학탐험대",
      "name": "똑똑수학탐험대",
      "group": "교과·맞춤형",
      "purpose": "초등 수학 개념과 연산을 놀이형 활동으로 익히는 학습 서비스",
      "counts": {
        "all": 3,
        "elementary": 3,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.7,
        "elementary": 3.5,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 34,
        "elementary": 13,
        "middle": 52,
        "high": 45
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "띵커벨",
          "북크리에이터",
          "심스페이스",
          "알지오매스키즈"
        ],
        "elementary": [
          "구글 클래스룸",
          "띵커벨",
          "북크리에이터",
          "심스페이스",
          "알지오매스키즈"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "멘티미터",
      "name": "멘티미터",
      "group": "퀴즈·참여",
      "purpose": "실시간 투표·설문·퀴즈·워드클라우드로 의견을 모으는 참여 도구",
      "counts": {
        "all": 3,
        "elementary": 1,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 1.7,
        "elementary": 1.2,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 35,
        "elementary": 43,
        "middle": 14,
        "high": 55
      },
      "related": {
        "all": [
          "패들렛",
          "캔바",
          "북크리에이터",
          "슬라이도",
          "ChatGPT"
        ],
        "elementary": [
          "북크리에이터",
          "슬라이도",
          "캔바",
          "패들렛"
        ],
        "middle": [
          "패들렛",
          "캔바",
          "ChatGPT",
          "Gemini",
          "SUNO"
        ],
        "high": []
      }
    },
    {
      "id": "우리반",
      "name": "우리반",
      "group": "학습관리",
      "purpose": "공지·기록·소통 등 담임의 학급 운영을 돕는 클래스 관리 도구",
      "counts": {
        "all": 3,
        "elementary": 2,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 1.7,
        "elementary": 2.3,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 36,
        "elementary": 29,
        "middle": 32,
        "high": 73
      },
      "related": {
        "all": [
          "심스페이스",
          "매쓰홀릭",
          "캔바",
          "클래스팅 AI",
          "클래시파이"
        ],
        "elementary": [
          "심스페이스",
          "매쓰홀릭",
          "캔바",
          "클래시파이",
          "패들렛"
        ],
        "middle": [
          "클래스팅 AI",
          "ZEP·젭퀴즈"
        ],
        "high": []
      }
    },
    {
      "id": "채움ai",
      "name": "채움AI",
      "group": "학습관리",
      "purpose": "학생 학습 데이터를 바탕으로 맞춤 지원과 피드백을 돕는 교육 서비스",
      "counts": {
        "all": 3,
        "elementary": 0,
        "middle": 3,
        "high": 0
      },
      "rates": {
        "all": 1.7,
        "elementary": 0,
        "middle": 5.9,
        "high": 0
      },
      "ranks": {
        "all": 37,
        "elementary": 86,
        "middle": 8,
        "high": 78
      },
      "related": {
        "all": [
          "클래스팅 AI",
          "Mizou",
          "QuillBot",
          "Snorkl",
          "Typecast"
        ],
        "elementary": [],
        "middle": [
          "클래스팅 AI",
          "Mizou",
          "QuillBot",
          "Snorkl",
          "Typecast"
        ],
        "high": []
      }
    },
    {
      "id": "카훗",
      "name": "카훗",
      "group": "퀴즈·참여",
      "purpose": "실시간 퀴즈와 설문으로 이해도와 참여를 확인하는 게임형 평가 도구",
      "counts": {
        "all": 3,
        "elementary": 0,
        "middle": 1,
        "high": 2
      },
      "rates": {
        "all": 1.7,
        "elementary": 0,
        "middle": 2,
        "high": 5.4
      },
      "ranks": {
        "all": 38,
        "elementary": 88,
        "middle": 35,
        "high": 11
      },
      "related": {
        "all": [
          "노션",
          "매쓰홀릭",
          "Clip Studio Paint",
          "Gemini",
          "Manus"
        ],
        "elementary": [],
        "middle": [
          "매쓰홀릭",
          "ZEP·젭퀴즈"
        ],
        "high": [
          "노션",
          "Clip Studio Paint",
          "Gemini",
          "Manus"
        ]
      }
    },
    {
      "id": "클래시파이",
      "name": "클래시파이",
      "group": "학습관리",
      "purpose": "학생 성향·관계 검사 결과로 상담과 생활지도를 돕는 학급관리 도구",
      "counts": {
        "all": 3,
        "elementary": 3,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.7,
        "elementary": 3.5,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 39,
        "elementary": 17,
        "middle": 83,
        "high": 82
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "심스페이스",
          "엔트리",
          "우리반"
        ],
        "elementary": [
          "캔바",
          "패들렛",
          "심스페이스",
          "엔트리",
          "우리반"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "러니",
      "name": "러니",
      "group": "언어·문해",
      "purpose": "읽기와 문해 활동을 지원하고 학습 과정을 관리하는 교육 서비스",
      "counts": {
        "all": 2,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 0,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 40,
        "elementary": 76,
        "middle": 13,
        "high": 46
      },
      "related": {
        "all": [
          "원아워",
          "체리팟",
          "클래스카드",
          "Brisk Teaching"
        ],
        "elementary": [],
        "middle": [
          "원아워",
          "체리팟",
          "클래스카드",
          "Brisk Teaching"
        ],
        "high": []
      }
    },
    {
      "id": "리드포스쿨",
      "name": "리드포스쿨",
      "group": "언어·문해",
      "purpose": "시선추적과 AI 분석을 활용해 읽기 과정을 진단하는 문해력 코스웨어",
      "counts": {
        "all": 2,
        "elementary": 2,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 2.3,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 41,
        "elementary": 24,
        "middle": 53,
        "high": 48
      },
      "related": {
        "all": [
          "패들렛",
          "블루킷",
          "엔트리",
          "캔바"
        ],
        "elementary": [
          "패들렛",
          "블루킷",
          "엔트리",
          "캔바"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "알지오매스키즈",
      "name": "알지오매스키즈",
      "group": "교과·맞춤형",
      "purpose": "초등 수학의 도형·측정·규칙 탐구를 지원하는 디지털 수학 도구",
      "counts": {
        "all": 2,
        "elementary": 2,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 2.3,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 42,
        "elementary": 27,
        "middle": 68,
        "high": 66
      },
      "related": {
        "all": [
          "똑똑수학탐험대",
          "심스페이스",
          "패들렛",
          "ZEP·젭퀴즈"
        ],
        "elementary": [
          "똑똑수학탐험대",
          "심스페이스",
          "패들렛",
          "ZEP·젭퀴즈"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "앰플리파이-클래스룸",
      "name": "앰플리파이 클래스룸",
      "group": "교과·맞춤형",
      "purpose": "디지털 교과 콘텐츠와 활동을 활용해 교과 수업을 지원하는 플랫폼",
      "counts": {
        "all": 2,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 0,
        "middle": 3.9,
        "high": 0
      },
      "ranks": {
        "all": 43,
        "elementary": 81,
        "middle": 17,
        "high": 68
      },
      "related": {
        "all": [
          "패들렛",
          "풀리수학"
        ],
        "elementary": [],
        "middle": [
          "패들렛",
          "풀리수학"
        ],
        "high": []
      }
    },
    {
      "id": "와우아이디어스",
      "name": "와우아이디어스",
      "group": "협업·공유",
      "purpose": "온라인 브레인스토밍으로 아이디어 생성·정리·평가·공유를 잇는 PBL 협업 도구",
      "counts": {
        "all": 2,
        "elementary": 2,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 2.3,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 44,
        "elementary": 28,
        "middle": 73,
        "high": 71
      },
      "related": {
        "all": [
          "캔바",
          "투닝",
          "패들렛",
          "AI마타수학"
        ],
        "elementary": [
          "캔바",
          "투닝",
          "패들렛",
          "AI마타수학"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "왓퀴즈",
      "name": "왓퀴즈",
      "group": "퀴즈·참여",
      "purpose": "문항 제작과 실시간 퀴즈 운영을 지원하는 수업 참여 도구",
      "counts": {
        "all": 2,
        "elementary": 1,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 1.2,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 45,
        "elementary": 52,
        "middle": 31,
        "high": 72
      },
      "related": {
        "all": [
          "뤼튼",
          "투닝",
          "패들렛",
          "Gemini",
          "Google Workspace"
        ],
        "elementary": [
          "패들렛",
          "Google Workspace",
          "ZEP·젭퀴즈"
        ],
        "middle": [
          "뤼튼",
          "투닝",
          "Gemini",
          "NotebookLM"
        ],
        "high": []
      }
    },
    {
      "id": "원아워",
      "name": "원아워",
      "group": "학습관리",
      "purpose": "과제 배부·제출·피드백과 진도 확인을 지원하는 학습관리 도구",
      "counts": {
        "all": 2,
        "elementary": 0,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 1.1,
        "elementary": 0,
        "middle": 2,
        "high": 2.7
      },
      "ranks": {
        "all": 46,
        "elementary": 83,
        "middle": 33,
        "high": 25
      },
      "related": {
        "all": [
          "러니",
          "클래스카드",
          "클리포"
        ],
        "elementary": [],
        "middle": [
          "러니"
        ],
        "high": [
          "클래스카드",
          "클리포"
        ]
      }
    },
    {
      "id": "퀴즈앤",
      "name": "퀴즈앤",
      "group": "퀴즈·참여",
      "purpose": "실시간 퀴즈와 게임형 활동으로 수업 참여를 지원하는 도구",
      "counts": {
        "all": 2,
        "elementary": 1,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 1.1,
        "elementary": 1.2,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 47,
        "elementary": 57,
        "middle": 81,
        "high": 28
      },
      "related": {
        "all": [
          "Snorkl",
          "ZEP·젭퀴즈"
        ],
        "elementary": [
          "ZEP·젭퀴즈"
        ],
        "middle": [],
        "high": [
          "Snorkl"
        ]
      }
    },
    {
      "id": "클래스팅",
      "name": "클래스팅",
      "group": "학습관리",
      "purpose": "수업 자료·과제·공지와 학생 소통을 지원하는 학습관리 플랫폼",
      "counts": {
        "all": 2,
        "elementary": 0,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 1.1,
        "elementary": 0,
        "middle": 2,
        "high": 2.7
      },
      "ranks": {
        "all": 48,
        "elementary": 89,
        "middle": 36,
        "high": 29
      },
      "related": {
        "all": [
          "띵커벨",
          "임팩트스페이스",
          "패들렛"
        ],
        "elementary": [],
        "middle": [
          "띵커벨"
        ],
        "high": [
          "임팩트스페이스",
          "패들렛"
        ]
      }
    },
    {
      "id": "키위티",
      "name": "키위티",
      "group": "언어·문해",
      "purpose": "학생 글쓰기 제출과 AI 대화·피드백을 지원하는 AI 글쓰기 코스웨어",
      "counts": {
        "all": 2,
        "elementary": 1,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 1.1,
        "elementary": 1.2,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 49,
        "elementary": 60,
        "middle": 86,
        "high": 33
      },
      "related": {
        "all": [
          "띵커벨",
          "매쓰홀릭",
          "심스페이스",
          "이음AI",
          "Gemini"
        ],
        "elementary": [
          "매쓰홀릭",
          "심스페이스"
        ],
        "middle": [],
        "high": [
          "띵커벨",
          "이음AI",
          "Gemini",
          "NotebookLM"
        ]
      }
    },
    {
      "id": "포커스팡",
      "name": "포커스팡",
      "group": "학습관리",
      "purpose": "학생의 디지털 학습 집중과 활동 관리를 지원하는 교실 도구",
      "counts": {
        "all": 2,
        "elementary": 1,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 1.2,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 50,
        "elementary": 63,
        "middle": 39,
        "high": 89
      },
      "related": {
        "all": [
          "클래스팅 AI",
          "패들렛",
          "풀리수학"
        ],
        "elementary": [
          "클래스팅 AI",
          "패들렛"
        ],
        "middle": [
          "풀리수학"
        ],
        "high": []
      }
    },
    {
      "id": "e-gpt",
      "name": "E-GPT",
      "group": "생성형 AI",
      "purpose": "교사가 목적에 맞는 교육용 챗봇을 구성해 활용하는 AI 서비스",
      "counts": {
        "all": 2,
        "elementary": 2,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 1.1,
        "elementary": 2.3,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 51,
        "elementary": 33,
        "middle": 97,
        "high": 98
      },
      "related": {
        "all": [
          "심스페이스",
          "통그라미",
          "투닝",
          "풀리수학",
          "Snorkl"
        ],
        "elementary": [
          "심스페이스",
          "통그라미",
          "투닝",
          "풀리수학",
          "Snorkl"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "redmenta",
      "name": "Redmenta",
      "group": "퀴즈·참여",
      "purpose": "디지털 활동지와 과제·평가를 제작하고 피드백하는 수업 도구",
      "counts": {
        "all": 2,
        "elementary": 0,
        "middle": 0,
        "high": 2
      },
      "rates": {
        "all": 1.1,
        "elementary": 0,
        "middle": 0,
        "high": 5.4
      },
      "ranks": {
        "all": 52,
        "elementary": 105,
        "middle": 105,
        "high": 15
      },
      "related": {
        "all": [
          "클래스카드",
          "Snorkl"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "클래스카드",
          "Snorkl"
        ]
      }
    },
    {
      "id": "다했니-다했어요",
      "name": "다했니·다했어요",
      "group": "학습관리",
      "purpose": "과제 배부·제출·확인과 학급 활동 기록을 돕는 학급관리 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 53,
        "elementary": 37,
        "middle": 49,
        "high": 43
      },
      "related": {
        "all": [
          "달달독해",
          "스쿨플랫",
          "캔바",
          "토도한글"
        ],
        "elementary": [
          "달달독해",
          "스쿨플랫",
          "캔바",
          "토도한글"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "달달독해",
      "name": "달달독해",
      "group": "언어·문해",
      "purpose": "초등 독해와 어휘를 단계적으로 연습하는 문해 학습 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 54,
        "elementary": 38,
        "middle": 50,
        "high": 44
      },
      "related": {
        "all": [
          "다했니·다했어요",
          "스쿨플랫",
          "캔바",
          "토도한글"
        ],
        "elementary": [
          "다했니·다했어요",
          "스쿨플랫",
          "캔바",
          "토도한글"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "데스모스",
      "name": "데스모스",
      "group": "교과·맞춤형",
      "purpose": "그래프·수식·활동지를 활용해 수학 개념 탐구를 지원하는 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 55,
        "elementary": 75,
        "middle": 51,
        "high": 18
      },
      "related": {
        "all": [
          "Gemini",
          "NotebookLM",
          "Snorkl"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "Gemini",
          "NotebookLM",
          "Snorkl"
        ]
      }
    },
    {
      "id": "뤼튼",
      "name": "뤼튼",
      "group": "생성형 AI",
      "purpose": "한국어 대화와 자료 생성을 지원하는 생성형 AI 서비스",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 56,
        "elementary": 77,
        "middle": 26,
        "high": 47
      },
      "related": {
        "all": [
          "왓퀴즈",
          "투닝",
          "Gemini",
          "NotebookLM"
        ],
        "elementary": [],
        "middle": [
          "왓퀴즈",
          "투닝",
          "Gemini",
          "NotebookLM"
        ],
        "high": []
      }
    },
    {
      "id": "리딩앤스쿨",
      "name": "리딩앤스쿨",
      "group": "언어·문해",
      "purpose": "학교 영어 읽기와 수준별 독서 활동을 지원하는 디지털 영어 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 57,
        "elementary": 39,
        "middle": 54,
        "high": 49
      },
      "related": {
        "all": [
          "리틀팍스",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "리틀팍스",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "리딩오션스쿨",
      "name": "리딩오션스쿨",
      "group": "언어·문해",
      "purpose": "전자책 읽기와 독서 활동·학습 관리를 제공하는 디지털 독서 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 58,
        "elementary": 40,
        "middle": 55,
        "high": 50
      },
      "related": {
        "all": [
          "스쿨플랫",
          "패들렛"
        ],
        "elementary": [
          "스쿨플랫",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "리로스쿨",
      "name": "리로스쿨",
      "group": "학습관리",
      "purpose": "학교 일정·진로·학습·학생 기록 업무를 통합 관리하는 학교 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 59,
        "elementary": 78,
        "middle": 56,
        "high": 20
      },
      "related": {
        "all": [
          "패들렛",
          "ChatGPT",
          "Claude"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "패들렛",
          "ChatGPT",
          "Claude"
        ]
      }
    },
    {
      "id": "리틀팍스",
      "name": "리틀팍스",
      "group": "언어·문해",
      "purpose": "애니메이션 영어동화와 단계별 읽기·듣기 콘텐츠를 제공하는 영어 학습 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 60,
        "elementary": 41,
        "middle": 57,
        "high": 51
      },
      "related": {
        "all": [
          "리딩앤스쿨",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "리딩앤스쿨",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "마이클ai",
      "name": "마이클AI",
      "group": "생성형 AI",
      "purpose": "학교 문서와 수업·업무 자료 작성을 지원하는 교원 업무 특화 AI",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 61,
        "elementary": 79,
        "middle": 27,
        "high": 52
      },
      "related": {
        "all": [
          "Claude",
          "Gemini"
        ],
        "elementary": [],
        "middle": [
          "Claude",
          "Gemini"
        ],
        "high": []
      }
    },
    {
      "id": "마인크래프트",
      "name": "마인크래프트",
      "group": "코딩·컴퓨팅",
      "purpose": "가상 세계에서 협력·설계·코딩 프로젝트를 수행하는 학습 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 62,
        "elementary": 42,
        "middle": 58,
        "high": 53
      },
      "related": {
        "all": [
          "띵커벨",
          "아이쌤GPT"
        ],
        "elementary": [
          "띵커벨",
          "아이쌤GPT"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "문제g",
      "name": "문제G",
      "group": "학습관리",
      "purpose": "문항 제작·배부·채점과 학습 결과 관리를 돕는 평가 운영 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 63,
        "elementary": 44,
        "middle": 59,
        "high": 56
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "매쓰홀릭",
          "이퓨처라이브러리",
          "Brisk Teaching"
        ],
        "elementary": [
          "구글 클래스룸",
          "매쓰홀릭",
          "이퓨처라이브러리",
          "Brisk Teaching"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "미리캔버스",
      "name": "미리캔버스",
      "group": "콘텐츠 제작",
      "purpose": "발표자료·카드뉴스·학습자료를 만드는 웹 기반 디자인 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 64,
        "elementary": 45,
        "middle": 60,
        "high": 57
      },
      "related": {
        "all": [
          "캡컷",
          "SUNO"
        ],
        "elementary": [
          "캡컷",
          "SUNO"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "빅카인즈",
      "name": "빅카인즈",
      "group": "협업·공유",
      "purpose": "뉴스 빅데이터를 검색·분석해 사회 현상 탐구를 지원하는 공공 데이터 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 65,
        "elementary": 46,
        "middle": 62,
        "high": 59
      },
      "related": {
        "all": [
          "캔바",
          "토도한글",
          "ZEP·젭퀴즈"
        ],
        "elementary": [
          "캔바",
          "토도한글",
          "ZEP·젭퀴즈"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "수학-아레나",
      "name": "수학 아레나",
      "group": "교과·맞춤형",
      "purpose": "게임형 문제 풀이로 수학 연습과 참여를 지원하는 학습 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 66,
        "elementary": 47,
        "middle": 63,
        "high": 61
      },
      "related": {
        "all": [
          "KOSIS"
        ],
        "elementary": [
          "KOSIS"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "슬라이도",
      "name": "슬라이도",
      "group": "퀴즈·참여",
      "purpose": "질문·투표·퀴즈·워드클라우드로 발표 참여를 높이는 상호작용 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 67,
        "elementary": 48,
        "middle": 64,
        "high": 62
      },
      "related": {
        "all": [
          "멘티미터",
          "북크리에이터",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "멘티미터",
          "북크리에이터",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "아이글",
      "name": "아이글",
      "group": "언어·문해",
      "purpose": "학생 글쓰기와 피드백 과정을 지원하는 디지털 글쓰기 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 68,
        "elementary": 80,
        "middle": 65,
        "high": 23
      },
      "related": {
        "all": [],
        "elementary": [],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "아이쌤gpt",
      "name": "아이쌤GPT",
      "group": "생성형 AI",
      "purpose": "교사의 수업 준비와 학교 업무를 지원하는 교육 특화 생성형 AI",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 69,
        "elementary": 49,
        "middle": 66,
        "high": 64
      },
      "related": {
        "all": [
          "띵커벨",
          "마인크래프트"
        ],
        "elementary": [
          "띵커벨",
          "마인크래프트"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "알지오매쓰2d",
      "name": "알지오매쓰2D",
      "group": "교과·맞춤형",
      "purpose": "수학 개념을 작도·그래프·조작 활동으로 탐구하는 수학 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 70,
        "elementary": 50,
        "middle": 69,
        "high": 67
      },
      "related": {
        "all": [
          "지니아튜터",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "지니아튜터",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "오르조-클래스",
      "name": "오르조 클래스",
      "group": "학습관리",
      "purpose": "문제 풀이와 학습 자료 배부·관리를 지원하는 학급용 학습 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 71,
        "elementary": 82,
        "middle": 71,
        "high": 24
      },
      "related": {
        "all": [
          "노션",
          "ChatGPT",
          "Claude",
          "Gemini"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "노션",
          "ChatGPT",
          "Claude",
          "Gemini"
        ]
      }
    },
    {
      "id": "온라인-교무실",
      "name": "온라인 교무실",
      "group": "학습관리",
      "purpose": "교직원 자료 공유와 학교 업무 협업을 위한 온라인 공간",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 72,
        "elementary": 51,
        "middle": 72,
        "high": 70
      },
      "related": {
        "all": [],
        "elementary": [],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "이음ai",
      "name": "이음AI",
      "group": "생성형 AI",
      "purpose": "교수학습 자료 생성과 수업 설계를 지원하는 교육용 AI 서비스",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 73,
        "elementary": 84,
        "middle": 74,
        "high": 26
      },
      "related": {
        "all": [
          "띵커벨",
          "키위티",
          "Gemini",
          "NotebookLM"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "띵커벨",
          "키위티",
          "Gemini",
          "NotebookLM"
        ]
      }
    },
    {
      "id": "이퓨처라이브러리",
      "name": "이퓨처라이브러리",
      "group": "언어·문해",
      "purpose": "레벨별 영어 전자책과 듣기·읽기 활동을 제공하는 영어 도서관",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 74,
        "elementary": 53,
        "middle": 75,
        "high": 74
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "매쓰홀릭",
          "문제G",
          "Brisk Teaching"
        ],
        "elementary": [
          "구글 클래스룸",
          "매쓰홀릭",
          "문제G",
          "Brisk Teaching"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "일프로-연산",
      "name": "일프로 연산",
      "group": "교과·맞춤형",
      "purpose": "학생 수준에 맞춘 수학 연산 연습을 제공하는 학습 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 75,
        "elementary": 54,
        "middle": 76,
        "high": 75
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "Class1234"
        ],
        "elementary": [
          "캔바",
          "패들렛",
          "Class1234"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "임팩트스페이스",
      "name": "임팩트스페이스",
      "group": "학습관리",
      "purpose": "학생 프로젝트와 활동 기록·공유를 지원하는 교육 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 76,
        "elementary": 85,
        "middle": 77,
        "high": 27
      },
      "related": {
        "all": [
          "클래스팅",
          "패들렛"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "클래스팅",
          "패들렛"
        ]
      }
    },
    {
      "id": "지니아튜터",
      "name": "지니아튜터",
      "group": "교과·맞춤형",
      "purpose": "국·영·수·사·과 과정과 AI 글쓰기 평가를 제공하는 교과 코스웨어",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 77,
        "elementary": 55,
        "middle": 79,
        "high": 77
      },
      "related": {
        "all": [
          "알지오매쓰2D",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "알지오매쓰2D",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "체리팟",
      "name": "체리팟",
      "group": "교과·맞춤형",
      "purpose": "교과 학습 활동과 학생별 과제·피드백을 지원하는 교육 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 78,
        "elementary": 87,
        "middle": 34,
        "high": 79
      },
      "related": {
        "all": [
          "러니",
          "클래스카드",
          "Brisk Teaching"
        ],
        "elementary": [],
        "middle": [
          "러니",
          "클래스카드",
          "Brisk Teaching"
        ],
        "high": []
      }
    },
    {
      "id": "캡컷",
      "name": "캡컷",
      "group": "콘텐츠 제작",
      "purpose": "자막·효과·AI 기능을 갖춘 영상 편집과 숏폼 제작 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 79,
        "elementary": 56,
        "middle": 80,
        "high": 80
      },
      "related": {
        "all": [
          "미리캔버스",
          "SUNO"
        ],
        "elementary": [
          "미리캔버스",
          "SUNO"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "클래스툴",
      "name": "클래스툴",
      "group": "학습관리",
      "purpose": "수업 활동과 학생 참여를 운영하는 교실 지원 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 80,
        "elementary": 58,
        "middle": 82,
        "high": 81
      },
      "related": {
        "all": [
          "패들렛"
        ],
        "elementary": [
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "키네마스터",
      "name": "키네마스터",
      "group": "콘텐츠 제작",
      "purpose": "모바일에서 영상과 음향을 편집하는 콘텐츠 제작 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 81,
        "elementary": 90,
        "middle": 84,
        "high": 31
      },
      "related": {
        "all": [
          "Elice AI"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "Elice AI"
        ]
      }
    },
    {
      "id": "키노트",
      "name": "키노트",
      "group": "콘텐츠 제작",
      "purpose": "애플 기기에서 발표자료와 시각 자료를 제작하는 프레젠테이션 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 82,
        "elementary": 91,
        "middle": 85,
        "high": 32
      },
      "related": {
        "all": [
          "Snorkl"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "Snorkl"
        ]
      }
    },
    {
      "id": "토도-시리즈",
      "name": "토도 시리즈",
      "group": "언어·문해",
      "purpose": "한글·수학·영어를 단계별 활동으로 연습하는 초기 학습 앱",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 83,
        "elementary": 61,
        "middle": 87,
        "high": 83
      },
      "related": {
        "all": [
          "클래스팅 AI"
        ],
        "elementary": [
          "클래스팅 AI"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "통그라미",
      "name": "통그라미",
      "group": "협업·공유",
      "purpose": "설문 설계와 통계 자료 분석을 지원하는 교육용 통계 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 84,
        "elementary": 62,
        "middle": 89,
        "high": 85
      },
      "related": {
        "all": [
          "투닝",
          "E-GPT",
          "SUNO"
        ],
        "elementary": [
          "투닝",
          "E-GPT",
          "SUNO"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "틴커캐드",
      "name": "틴커캐드",
      "group": "코딩·컴퓨팅",
      "purpose": "3D 설계와 전자회로·코딩 시뮬레이션을 지원하는 제작 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 85,
        "elementary": 92,
        "middle": 37,
        "high": 87
      },
      "related": {
        "all": [
          "캔바",
          "패들렛",
          "Gemini"
        ],
        "elementary": [],
        "middle": [
          "캔바",
          "패들렛",
          "Gemini"
        ],
        "high": []
      }
    },
    {
      "id": "파파고",
      "name": "파파고",
      "group": "언어·문해",
      "purpose": "텍스트·이미지·음성 번역을 지원하는 다국어 번역 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 86,
        "elementary": 93,
        "middle": 38,
        "high": 88
      },
      "related": {
        "all": [
          "캔바",
          "패들렛"
        ],
        "elementary": [],
        "middle": [
          "캔바",
          "패들렛"
        ],
        "high": []
      }
    },
    {
      "id": "픽스톤",
      "name": "픽스톤",
      "group": "콘텐츠 제작",
      "purpose": "캐릭터와 장면을 조합해 만화와 이야기를 만드는 디지털 스토리텔링 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 87,
        "elementary": 94,
        "middle": 40,
        "high": 91
      },
      "related": {
        "all": [
          "캔바",
          "패들렛"
        ],
        "elementary": [],
        "middle": [
          "캔바",
          "패들렛"
        ],
        "high": []
      }
    },
    {
      "id": "ai-아크수학",
      "name": "AI 아크수학",
      "group": "교과·맞춤형",
      "purpose": "학생 수준 진단과 맞춤형 수학 학습을 지원하는 AI 코스웨어",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 88,
        "elementary": 64,
        "middle": 91,
        "high": 92
      },
      "related": {
        "all": [
          "ZEP·젭퀴즈"
        ],
        "elementary": [
          "ZEP·젭퀴즈"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "ai마타수학",
      "name": "AI마타수학",
      "group": "교과·맞춤형",
      "purpose": "진단 결과에 따라 개별 수학 문항과 학습 경로를 제공하는 AI 코스웨어",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 89,
        "elementary": 65,
        "middle": 92,
        "high": 93
      },
      "related": {
        "all": [
          "와우아이디어스",
          "패들렛"
        ],
        "elementary": [
          "와우아이디어스",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "aice",
      "name": "AICE",
      "group": "코딩·컴퓨팅",
      "purpose": "AI 개념과 데이터 활용 역량을 학습·평가하는 교육 프로그램",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 90,
        "elementary": 95,
        "middle": 93,
        "high": 34
      },
      "related": {
        "all": [
          "스쿨플랫"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "스쿨플랫"
        ]
      }
    },
    {
      "id": "algeomath",
      "name": "AlgeoMath",
      "group": "교과·맞춤형",
      "purpose": "대수와 기하를 시각적으로 조작하며 탐구하는 수학 학습 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 91,
        "elementary": 96,
        "middle": 41,
        "high": 94
      },
      "related": {
        "all": [
          "MS OneNote",
          "MS Teams"
        ],
        "elementary": [],
        "middle": [
          "MS OneNote",
          "MS Teams"
        ],
        "high": []
      }
    },
    {
      "id": "class1234",
      "name": "Class1234",
      "group": "학습관리",
      "purpose": "학생 일기·보상·댓글을 활용해 학급 소통과 참여를 돕는 운영 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 92,
        "elementary": 66,
        "middle": 94,
        "high": 96
      },
      "related": {
        "all": [
          "일프로 연산",
          "캔바",
          "패들렛"
        ],
        "elementary": [
          "일프로 연산",
          "캔바",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "clip-studio-paint",
      "name": "Clip Studio Paint",
      "group": "콘텐츠 제작",
      "purpose": "일러스트·만화·애니메이션 제작을 지원하는 디지털 드로잉 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 93,
        "elementary": 97,
        "middle": 95,
        "high": 35
      },
      "related": {
        "all": [
          "카훗",
          "Gemini"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "카훗",
          "Gemini"
        ]
      }
    },
    {
      "id": "delightex",
      "name": "Delightex",
      "group": "코딩·컴퓨팅",
      "purpose": "3D 공간을 만들고 코딩·VR·AR로 확장하는 실감형 창작 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 94,
        "elementary": 67,
        "middle": 96,
        "high": 97
      },
      "related": {
        "all": [
          "Skybox AI"
        ],
        "elementary": [
          "Skybox AI"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "elice-ai",
      "name": "Elice AI",
      "group": "생성형 AI",
      "purpose": "AI 학습·실습과 교육 콘텐츠 운영을 지원하는 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 95,
        "elementary": 98,
        "middle": 98,
        "high": 36
      },
      "related": {
        "all": [
          "키네마스터"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "키네마스터"
        ]
      }
    },
    {
      "id": "gamma",
      "name": "Gamma",
      "group": "콘텐츠 제작",
      "purpose": "AI로 발표자료·문서·웹페이지 초안을 만드는 프레젠테이션 저작 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 96,
        "elementary": 99,
        "middle": 99,
        "high": 37
      },
      "related": {
        "all": [
          "클래스팅 AI",
          "ChatGPT",
          "Claude",
          "Gemini",
          "MS Teams"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "클래스팅 AI",
          "ChatGPT",
          "Claude",
          "Gemini",
          "MS Teams"
        ]
      }
    },
    {
      "id": "kosis",
      "name": "KOSIS",
      "group": "협업·공유",
      "purpose": "국가 통계 자료를 검색하고 시각화해 탐구에 활용하는 공공 데이터 서비스",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 97,
        "elementary": 68,
        "middle": 100,
        "high": 99
      },
      "related": {
        "all": [
          "수학 아레나"
        ],
        "elementary": [
          "수학 아레나"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "kuula",
      "name": "Kuula",
      "group": "콘텐츠 제작",
      "purpose": "360도 사진을 연결해 가상 전시와 투어를 만드는 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 98,
        "elementary": 100,
        "middle": 101,
        "high": 38
      },
      "related": {
        "all": [
          "플랭스쿨",
          "Mizou"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "플랭스쿨",
          "Mizou"
        ]
      }
    },
    {
      "id": "manus",
      "name": "Manus",
      "group": "생성형 AI",
      "purpose": "조사·정리·콘텐츠 제작 과정을 수행하는 AI 에이전트",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 99,
        "elementary": 101,
        "middle": 102,
        "high": 39
      },
      "related": {
        "all": [
          "노션",
          "카훗"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "노션",
          "카훗"
        ]
      }
    },
    {
      "id": "ms-리딩-프로그레스",
      "name": "MS 리딩 프로그레스",
      "group": "언어·문해",
      "purpose": "학생의 소리 내어 읽기를 기록하고 읽기 유창성을 확인하는 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 100,
        "elementary": 69,
        "middle": 103,
        "high": 100
      },
      "related": {
        "all": [
          "매쓰홀릭",
          "Gemini"
        ],
        "elementary": [
          "매쓰홀릭",
          "Gemini"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "ms-onenote",
      "name": "MS OneNote",
      "group": "협업·공유",
      "purpose": "디지털 필기와 수업 자료 정리·공유를 지원하는 전자 노트",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 101,
        "elementary": 102,
        "middle": 43,
        "high": 101
      },
      "related": {
        "all": [
          "AlgeoMath",
          "MS Teams"
        ],
        "elementary": [],
        "middle": [
          "AlgeoMath",
          "MS Teams"
        ],
        "high": []
      }
    },
    {
      "id": "quillbot",
      "name": "QuillBot",
      "group": "생성형 AI",
      "purpose": "영문 문장 바꾸기·문법 확인·요약을 지원하는 글쓰기 보조 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 102,
        "elementary": 104,
        "middle": 44,
        "high": 102
      },
      "related": {
        "all": [
          "채움AI",
          "Mizou"
        ],
        "elementary": [],
        "middle": [
          "채움AI",
          "Mizou"
        ],
        "high": []
      }
    },
    {
      "id": "read-along",
      "name": "Read Along",
      "group": "언어·문해",
      "purpose": "소리 내어 읽기와 즉각적인 발음 피드백을 지원하는 읽기 학습 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 103,
        "elementary": 70,
        "middle": 104,
        "high": 103
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "Gemini"
        ],
        "elementary": [
          "구글 클래스룸",
          "Gemini"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "sen에듀",
      "name": "SEN에듀",
      "group": "학습관리",
      "purpose": "교육 자료와 학교 수업 운영을 지원하는 서울교육 플랫폼",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 104,
        "elementary": 71,
        "middle": 106,
        "high": 105
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "패들렛"
        ],
        "elementary": [
          "구글 클래스룸",
          "패들렛"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "skybox-ai",
      "name": "Skybox AI",
      "group": "콘텐츠 제작",
      "purpose": "텍스트 지시로 360도 배경과 가상 공간 이미지를 만드는 AI 도구",
      "counts": {
        "all": 1,
        "elementary": 1,
        "middle": 0,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 1.2,
        "middle": 0,
        "high": 0
      },
      "ranks": {
        "all": 105,
        "elementary": 72,
        "middle": 107,
        "high": 106
      },
      "related": {
        "all": [
          "Delightex"
        ],
        "elementary": [
          "Delightex"
        ],
        "middle": [],
        "high": []
      }
    },
    {
      "id": "typecast",
      "name": "Typecast",
      "group": "콘텐츠 제작",
      "purpose": "AI 음성과 가상 인물로 오디오·영상 콘텐츠를 만드는 제작 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 106,
        "elementary": 106,
        "middle": 46,
        "high": 107
      },
      "related": {
        "all": [
          "채움AI",
          "Snorkl"
        ],
        "elementary": [],
        "middle": [
          "채움AI",
          "Snorkl"
        ],
        "high": []
      }
    },
    {
      "id": "veo3",
      "name": "Veo3",
      "group": "콘텐츠 제작",
      "purpose": "텍스트와 이미지 지시를 바탕으로 영상을 생성하는 AI 도구",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 0,
        "high": 1
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 0,
        "high": 2.7
      },
      "ranks": {
        "all": 107,
        "elementary": 107,
        "middle": 108,
        "high": 41
      },
      "related": {
        "all": [
          "구글 클래스룸",
          "ChatGPT"
        ],
        "elementary": [],
        "middle": [],
        "high": [
          "구글 클래스룸",
          "ChatGPT"
        ]
      }
    },
    {
      "id": "vllo",
      "name": "VLLO",
      "group": "콘텐츠 제작",
      "purpose": "모바일에서 자막·효과·음악을 편집하는 쉬운 영상 제작 앱",
      "counts": {
        "all": 1,
        "elementary": 0,
        "middle": 1,
        "high": 0
      },
      "rates": {
        "all": 0.6,
        "elementary": 0,
        "middle": 2,
        "high": 0
      },
      "ranks": {
        "all": 108,
        "elementary": 108,
        "middle": 47,
        "high": 108
      },
      "related": {
        "all": [
          "캔바",
          "클리포",
          "Claude"
        ],
        "elementary": [],
        "middle": [
          "캔바",
          "클리포",
          "Claude"
        ],
        "high": []
      }
    }
  ],
  "groups": [
    {
      "name": "협업·공유",
      "counts": {
        "all": 74,
        "elementary": 41,
        "middle": 19,
        "high": 14
      },
      "rates": {
        "all": 42.5,
        "elementary": 47.7,
        "middle": 37.3,
        "high": 37.8
      },
      "color": "#18a7e0",
      "text": "학생 결과물과 아이디어를 함께 모아 공유"
    },
    {
      "name": "언어·문해",
      "counts": {
        "all": 30,
        "elementary": 20,
        "middle": 5,
        "high": 5
      },
      "rates": {
        "all": 17.2,
        "elementary": 23.3,
        "middle": 9.8,
        "high": 13.5
      },
      "color": "#e39a20",
      "text": "읽기·쓰기·영어 등 언어 학습을 지원"
    },
    {
      "name": "퀴즈·참여",
      "counts": {
        "all": 46,
        "elementary": 18,
        "middle": 15,
        "high": 13
      },
      "rates": {
        "all": 26.4,
        "elementary": 20.9,
        "middle": 29.4,
        "high": 35.1
      },
      "color": "#f06a4e",
      "text": "수업 중 참여와 빠른 확인을 지원"
    },
    {
      "name": "교과·맞춤형",
      "counts": {
        "all": 32,
        "elementary": 22,
        "middle": 8,
        "high": 2
      },
      "rates": {
        "all": 18.4,
        "elementary": 25.6,
        "middle": 15.7,
        "high": 5.4
      },
      "color": "#7dbd35",
      "text": "교과 진단과 개인별 연습을 수업에 연결"
    },
    {
      "name": "생성형 AI",
      "counts": {
        "all": 50,
        "elementary": 13,
        "middle": 20,
        "high": 17
      },
      "rates": {
        "all": 28.7,
        "elementary": 15.1,
        "middle": 39.2,
        "high": 45.9
      },
      "color": "#7b68d9",
      "text": "교사의 자료 제작과 탐색·분석을 지원"
    },
    {
      "name": "콘텐츠 제작",
      "counts": {
        "all": 61,
        "elementary": 33,
        "middle": 16,
        "high": 12
      },
      "rates": {
        "all": 35.1,
        "elementary": 38.4,
        "middle": 31.4,
        "high": 32.4
      },
      "color": "#ef79b7",
      "text": "글·이미지·영상·음악 결과물을 제작"
    },
    {
      "name": "학습관리",
      "counts": {
        "all": 49,
        "elementary": 30,
        "middle": 11,
        "high": 8
      },
      "rates": {
        "all": 28.2,
        "elementary": 34.9,
        "middle": 21.6,
        "high": 21.6
      },
      "color": "#9a6b32",
      "text": "과제·진도·상담·학급 운영을 관리"
    },
    {
      "name": "코딩·컴퓨팅",
      "counts": {
        "all": 8,
        "elementary": 6,
        "middle": 1,
        "high": 1
      },
      "rates": {
        "all": 4.6,
        "elementary": 7,
        "middle": 2,
        "high": 2.7
      },
      "color": "#66829a",
      "text": "코딩·컴퓨팅 사고와 디지털 제작을 지원"
    }
  ]
};

export const teacherWebAppSummary: TeacherWebAppSummary = {
  "counts": {
    "all": 24,
    "elementary": 8,
    "middle": 12,
    "high": 4
  },
  "purposes": [
    {
      "name": "수업 활동",
      "description": "글쓰기·토의·교과 탐구처럼 수업 흐름에 맞춘 활동 도구"
    },
    {
      "name": "평가·피드백",
      "description": "결과 조회·자동 채점·서술형 피드백과 학습 데이터 확인"
    },
    {
      "name": "학급 운영",
      "description": "자리·역할 선택, 과제와 프로젝트 진행 상황 관리"
    },
    {
      "name": "탐구·시뮬레이션",
      "description": "전기회로·지진 등 직접 조작하며 개념을 확인하는 웹 도구"
    }
  ],
  "examples": [
    {
      "title": "과학 실험 데이터 시각화",
      "description": "실험 결과를 입력하고 그래프로 비교해 탐구와 설명을 돕는 웹앱",
      "level": "middle",
      "purpose": "수업 활동"
    },
    {
      "title": "서술형 피드백 도구",
      "description": "평가기준을 바탕으로 학생 글을 검토하고 다음 수정 방향을 안내하는 웹앱",
      "level": "middle",
      "purpose": "평가·피드백"
    },
    {
      "title": "학급 운영 프로그램",
      "description": "자리와 역할 선택처럼 반복되는 학급 운영을 간단히 처리하는 웹 프로그램",
      "level": "elementary",
      "purpose": "학급 운영"
    },
    {
      "title": "문해력 맞춤 학습 도구",
      "description": "학습 데이터를 바탕으로 읽기 수준과 다음 활동을 연결하는 자체 도구",
      "level": "elementary",
      "purpose": "수업 활동"
    },
    {
      "title": "전기회로·지진 탐구 시뮬레이터",
      "description": "조건을 직접 바꾸며 과학 개념과 결과의 변화를 확인하는 웹 기반 실험 도구",
      "level": "middle",
      "purpose": "탐구·시뮬레이션"
    },
    {
      "title": "프로젝트 진행 관리",
      "description": "팀별 진행 상황과 제출물을 확인해 필요한 피드백을 빠르게 제공하는 웹앱",
      "level": "high",
      "purpose": "학급 운영"
    },
    {
      "title": "기초학력 수업 도입 도구",
      "description": "학생이 수업에 들어가기 전 핵심 개념과 준비 상태를 확인하는 웹앱",
      "level": "high",
      "purpose": "수업 활동"
    }
  ],
  "insights": {
    "all": {
      "headline": "기성 도구를 고르는 데서 직접 필요한 기능을 만드는 단계로 넓어졌습니다.",
      "detail": "수업·평가·학급 운영에서 반복되는 불편을 작게 해결하는 웹앱이 많았습니다. 완성도보다 실제 수업에서 바로 고쳐 쓰고 동료와 공유하는 방식이 두드러집니다.",
      "question": "학교 안에서 계속 사용할 사람, 수정할 사람, 학생 정보 처리 기준을 함께 정했나요?"
    },
    "elementary": {
      "headline": "초등에서는 학급 운영과 문해·맞춤 학습을 돕는 작은 도구가 눈에 띕니다.",
      "detail": "자리·역할 선택, 읽기 진단, 학급별 학습관리처럼 담임교사의 반복 업무와 학생별 지원을 연결한 사례가 확인됩니다.",
      "question": "학생이 혼자 계정을 만들지 않아도 교사가 수업 안에서 안전하게 운영할 수 있나요?"
    },
    "middle": {
      "headline": "중등에서는 교과 평가와 탐구를 수업에 맞게 바꾼 웹앱이 가장 다양합니다.",
      "detail": "과학 시뮬레이션, 글쓰기 피드백, 수행평가 조회, 체육 자동채점처럼 교과의 구체적인 평가 장면을 해결하려는 개발이 많았습니다.",
      "question": "자동 결과를 교사의 관찰과 피드백으로 다시 확인하는 절차가 있나요?"
    },
    "high": {
      "headline": "고등에서는 프로젝트 관리와 교과 전문 활동을 지원하는 도구가 나타납니다.",
      "detail": "온라인 저지, 팀 프로젝트 진행 관리, 기초학력 지원처럼 교과와 진로 활동의 복잡한 운영을 줄이려는 사례가 확인됩니다.",
      "question": "담당 교사가 바뀌어도 유지할 수 있도록 사용법과 수정 기록을 남기고 있나요?"
    }
  }
};
